### ISSUE TITLE
Improve error handling for http calls

### ISSUE THREAD

**Issue by JulianGindi** [istrategylabs/franklin-api#53]
- Errors from third-party calls should be handled at a higher level in the code

**Comment by oudeismetis** [comment]
When we refactor this, make sure we have a way to capture situations like 422 response from github webhook creation. In that situation specifically, we want to do one of two things 1) Ignore and just move on as the webhook already exists 2) Make a 2nd call the github to update the existing webhook so that it's definitely doing what we expect.
